PDFS=	Board_Users_Manual_XMC_2Go_Kit_with_XMC1100_R1.0.pdf \
	Infineon-xmc1100-AA_rm-UM-v01_01-EN.pdf \
	ARM7-TDMI-manual-pt3.pdf \
	DDI0419C_arm_architecture_v6m_reference_manual.pdf

all:	$(PDFS)


Board_Users_Manual_XMC_2Go_Kit_with_XMC1100_R1.0.pdf:	
	wget 'http://www.infineon.com/dgdl/Board_Users_Manual_XMC_2Go_Kit_with_XMC1100_R1.0.pdf?folderId=5546d4694909da4801490a0745e10595&fileId=db3a3043444ee5dc014453d6c75078c6&ack=t' -O $@

Infineon-xmc1100-AA_rm-UM-v01_01-EN.pdf:	
	wget 'http://www.infineon.com/dgdl/xmc1100_rm_v1+0_2013_03.pdf?folderId=db3a30433580b3710135a47f3eb76c98&fileId=db3a30433cfb5caa013d1600856033eb&ack=t' -O $@

DDI0419C_arm_architecture_v6m_reference_manual.pdf:	
	wget 'http://ecee.colorado.edu/ecen3000/labs/lab3/files/DDI0419C_arm_architecture_v6m_reference_manual.pdf' -O $@

# APP_XMC1000_XMC4000_USIC_V1_0.pdf:	
# 	wget 'https://www.infineon.com/dgdl/APP_XMC1000_XMC4000_USIC_V1_0.pdf?folderId=5546d4694909da4801490a075148059c&fileId=5546d461454603990145cc5e5e7d56de&ack=t' -O $@

# DEV_XMC1000_XMC4000_CCU4_v1_0.pdf:	
# 	wget 'http://www.infineon.com/dgdl/DEV_XMC1000_XMC4000_CCU4_v1_0.pdf?folderId=5546d4694909da4801490a075148059c&fileId=db3a30433e78ea82013e7e0c2ba40576&ack=t' -O $@

ARM7-TDMI-manual-pt3.pdf:	
	wget 'https://ece.uwaterloo.ca/~ece222/ARM/ARM7-TDMI-manual-pt3.pdf' -O $@
